version = 0.1

[default.global.parameters]
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

# ── dev ──
[dev.deploy.parameters]
stack_name = "ccs-ticket-backend-dev"
region = "us-east-1"
s3_prefix  = "ccs-ticket-backend-dev"
parameter_overrides = "Stage=dev"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

# ── prod ──
[prod.deploy.parameters]
stack_name = "ccs-ticket-backend-prod"
region = "us-east-1"
s3_prefix  = "ccs-ticket-backend-prod"
parameter_overrides = "Stage=prod"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
